### PR TITLE
Fault tolerance

### PR DESCRIPTION
**Pull request by b-long**
**_Do not merge yet**_ (This branch represents a work-in-progerss).  

As I'm working to make the SPB function without a particular node, I wanted to document a development workflow.  For rendered version of the main document, see here: https://github.com/b-long/packagebuilder/blob/feature/fault-tolerance/documentation/Developing.md

### CODE REVIEW

**Comment by b-long** [comment]
NB: I'm using this package to test changes: https://github.com/Bioconductor/packagebuilder/issues/15#issuecomment-159715786

**Comment by b-long** [comment]
FYI @mtmorgan , I'm applying your commits atop this branch.

**Comment by b-long** [comment]
@dtenenba Mind taking a look at this branch?  Morelia builds should now be disabled, and I think it's worth it to consider merging to master & deploying to production.

**Comment by b-long** [comment]
Note to anyone reviewing this PR, I'm currently depending on a change to the [BBS](https://github.com/Bioconductor/BBS/pull/40) (already merged to `Bioconductor:feature/migrate_back_to_hutch`).  Make sure your local copy of the BBS has this change.

The code in BBS previously did something like : 

```
key = hostname # Hostname of the machine executing the SPB 
configuration = dictionary[key] # Get configuration specific to that host
```

Since we don't want every developer to have to modify either (1) their hostname or (2) the hard-coded configuration, the code referenced above is a workaround.

**Comment by b-long** [comment]
@dtenenba Any objection to giving this a whirl in production tomorrow morning?

**Comment by dtenenba** [comment]
@b-long No objection.

**Pull request merged**
